name: user_repository
description: "Dart package that handles users"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable:
  firebase_auth: ^4.17.8
  cloud_firestore:
  firebase_storage:
  firebase_messaging:
  firebase_core:
  post_repository:
    path: ../post_repository 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
